import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Locale;

/**
 * Processes the individual links generated by textProcessor.createLinks()
 */
public class ProcessBookLinks {
    String section;
    ArrayList<String> books = new ArrayList<>();

    /**
     * ArrayList holding individual books gets passed here;
     * try-catch used to deal with invalid entries;
     * the full collection of books is processed to text file
     * @param book
     */
    public void runBooks(String book) {
        Document gesta = null;
        try {
            gesta = Jsoup.connect(book).get();
        } catch (IOException e) {
            e.printStackTrace();
        }
        // placing link into String array[0] and cleaning text
        // each replace() deals with one punctuation token
        assert gesta != null;
        section = gesta.text()
                .toLowerCase(Locale.ROOT)
                .replace("gesta francorum medieval latin the latin library the classics page", "")
                .replace(",", "")
                .replace(".", "")
                .replace(":", "")
                .replace(";", "")
                .replace("?", "")
                .replace("!", "")
                .replace("[", "")
                .replace("]", "")
                .replace("(","")
                .replace(")","");
        System.out.println(section); // print to console to test
        books.add(section);
        writeToText();
    }

    /**
     * Specific method call to write the processed text to a file
     */
    public void writeToText(){
        writeFile("GestaFrancorum.txt", books);
    }

    /**
     * Generic method definition to write text to file
     * Text is held in an array list and iterated through
     * @param fileName
     * @param text
     */
    public void writeFile(String fileName, ArrayList<String> text){
        try {
            FileWriter fileWriter = new FileWriter(fileName);
            PrintWriter printWriter = new PrintWriter(fileWriter);
            for (String s : text) {
                printWriter.println(s);
            }
            printWriter.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
